/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aragon.ico.inicio;

import aragon.ico.implementacion.Juego;

/**
 *
 * @author makin
 */
public class Inicio extends javax.swing.JFrame {

    private Juego game;
    boolean duece = false;
    int round = 1;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        game = new Juego();
        setLocationRelativeTo(null);
        
        jLServidorNombre.setText(game.getServidor().getNombre());
        jLServidorPuntos.setText(String.valueOf(game.getServidor().getPuntos()));
        jBServidor.setText(game.getServidor().getNombre());
        
        jLReceptorNombre.setText(game.getReceptor().getNombre());
        jLReceptorPuntos.setText(String.valueOf(game.getReceptor().getPuntos()));
        jBReceptor.setText(game.getReceptor().getNombre());
        
        jLComentarios.setText("Que inicie el juego");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPServidor = new javax.swing.JPanel();
        jLServidorNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLServidorPuntos = new javax.swing.JLabel();
        jPReceptor = new javax.swing.JPanel();
        jLReceptorNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLReceptorPuntos = new javax.swing.JLabel();
        jPTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPEvento = new javax.swing.JPanel();
        jBServidor = new javax.swing.JButton();
        jBReceptor = new javax.swing.JButton();
        jLRound = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLComentarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad Extra");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPServidor.setBackground(new java.awt.Color(48, 237, 0));

        jLServidorNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLServidorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLServidorNombre.setText("Jugador 1");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aragon/ico/imagenes/icons8_Sonic_the_Hedgehog_96px.png"))); // NOI18N

        jLServidorPuntos.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLServidorPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLServidorPuntos.setText("0");

        javax.swing.GroupLayout jPServidorLayout = new javax.swing.GroupLayout(jPServidor);
        jPServidor.setLayout(jPServidorLayout);
        jPServidorLayout.setHorizontalGroup(
            jPServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLServidorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPServidorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLServidorPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPServidorLayout.setVerticalGroup(
            jPServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPServidorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLServidorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLServidorPuntos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 260));

        jPReceptor.setBackground(new java.awt.Color(0, 87, 223));

        jLReceptorNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLReceptorNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLReceptorNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLReceptorNombre.setText("Jugador 2");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aragon/ico/imagenes/icons8_Crash_Bandicoot_96px.png"))); // NOI18N

        jLReceptorPuntos.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLReceptorPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jLReceptorPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLReceptorPuntos.setText("0");

        javax.swing.GroupLayout jPReceptorLayout = new javax.swing.GroupLayout(jPReceptor);
        jPReceptor.setLayout(jPReceptorLayout);
        jPReceptorLayout.setHorizontalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPReceptorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLReceptorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPReceptorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLReceptorPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPReceptorLayout.setVerticalGroup(
            jPReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReceptorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLReceptorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLReceptorPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 220, 260));

        jPTitulo.setBackground(new java.awt.Color(0, 54, 96));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tennis Kata");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 60));

        jPEvento.setBackground(new java.awt.Color(0, 54, 96));

        jBServidor.setBackground(new java.awt.Color(48, 237, 0));
        jBServidor.setText("jButton1");
        jBServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBServidorActionPerformed(evt);
            }
        });

        jBReceptor.setBackground(new java.awt.Color(0, 87, 223));
        jBReceptor.setText("jButton2");
        jBReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReceptorActionPerformed(evt);
            }
        });

        jLRound.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLRound.setForeground(new java.awt.Color(255, 255, 255));
        jLRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRound.setText("ROUND 1");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Vencedor?");

        jLComentarios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLComentarios.setForeground(new java.awt.Color(255, 255, 255));
        jLComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLComentarios.setText("Comentarios");

        javax.swing.GroupLayout jPEventoLayout = new javax.swing.GroupLayout(jPEvento);
        jPEvento.setLayout(jPEventoLayout);
        jPEventoLayout.setHorizontalGroup(
            jPEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEventoLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(jPEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEventoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jBServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBReceptor)
                .addGap(69, 69, 69))
            .addGroup(jPEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPEventoLayout.setVerticalGroup(
            jPEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEventoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBServidor)
                    .addComponent(jBReceptor))
                .addGap(26, 26, 26)
                .addComponent(jLComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 440, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBServidorActionPerformed
        if (!duece) {
            game.ronda(0);
            jLServidorPuntos.setText(String.valueOf(game.getServidor().getPuntos()));
            narracion();
        }
        else{
            game.deuce(game.getServidor(), game.getReceptor());
            jLServidorPuntos.setText(game.getServidor().getDeuce());
            jLReceptorPuntos.setText(String.valueOf(game.getReceptor().getPuntos()));
            narracion();
        }
        
        if (game.hayDeuce()) {
            duece = true;
        }
        
        if (game.getServidor().getGano()) {
            jBReceptor.setEnabled(false);
            jBServidor.setEnabled(false);
        }
        
        round++;
        jLRound.setText("ROUND " + round);
    }//GEN-LAST:event_jBServidorActionPerformed

    private void jBReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReceptorActionPerformed
        if (!duece) {
            game.ronda(1);
            jLReceptorPuntos.setText(String.valueOf(game.getReceptor().getPuntos()));
            narracion();
        }
        else{
            game.deuce(game.getReceptor(), game.getServidor());
            jLReceptorPuntos.setText(game.getReceptor().getDeuce());
            jLServidorPuntos.setText(String.valueOf(game.getServidor().getPuntos()));
            narracion();
        }
        
        if (game.hayDeuce()) {
            duece = true;
        }
        
        if (game.getReceptor().getGano()) {
            jBReceptor.setEnabled(false);
            jBServidor.setEnabled(false);
        }
        
        round++;
        jLRound.setText("ROUND " + round);
    }//GEN-LAST:event_jBReceptorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReceptor;
    private javax.swing.JButton jBServidor;
    private javax.swing.JLabel jLComentarios;
    private javax.swing.JLabel jLReceptorNombre;
    private javax.swing.JLabel jLReceptorPuntos;
    private javax.swing.JLabel jLRound;
    private javax.swing.JLabel jLServidorNombre;
    private javax.swing.JLabel jLServidorPuntos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPEvento;
    private javax.swing.JPanel jPReceptor;
    private javax.swing.JPanel jPServidor;
    private javax.swing.JPanel jPTitulo;
    // End of variables declaration//GEN-END:variables

    public void narracion(){
        if (!duece) {
            if (game.getServidor().getPuntos() > game.getReceptor().getPuntos()) {
                jLComentarios.setText(game.getServidor().getNombre() + " va ganando");
            }
            else if (game.getReceptor().getPuntos() > game.getServidor().getPuntos()) {
                jLComentarios.setText(game.getReceptor().getNombre() + " va ganando");
            }
            else {
                if (game.hayDeuce()) {
                    jLComentarios.setText("***** DEUCE *****");
                }
                else if (game.getServidor().getPuntos() == game.getReceptor().getPuntos()) {
                    jLComentarios.setText("El marcador se empató");
                }
            }
        }
        else{
            if (game.getServidor().getDeuce().equals("A")) {
                jLComentarios.setText("Punto para " + game.getServidor().getNombre());
            }
            else if(game.getReceptor().getDeuce().equals("A")){
                jLComentarios.setText("Punto para " + game.getReceptor().getNombre());
            }
        }
        
        if (game.getServidor().getGano()) {
            jLComentarios.setText("Juego finalizado. Ganador " + game.getServidor().getNombre());
        }
        else if (game.getReceptor().getGano()) {
            jLComentarios.setText("Juego finalizado. Ganador " + game.getReceptor().getNombre());
        }
    }

}
